### ISSUE TITLE
Failed with File not Found

### ISSUE THREAD

**Issue by MrHinsh** [Ant0wan/openai-pr#23]
https://github.com/nkdAgility/azure-devops-migration-tools/actions/runs/9960662301

**Comment by Ant0wan** [comment]
Hi @MrHinsh , you need to specify a '.github/PULL_REQUEST_TEMPLATE.md' in your repository.
cf: https://github.com/Ant0wan/openai-pr/blob/main/.github/PULL_REQUEST_TEMPLATE.md
Have a nice day

**Comment by MrHinsh** [comment]
@Ant0wan, what is the template's purpose, and how do its contents affect the GTP output?

**Comment by Ant0wan** [comment]
@MrHinsh I am archiving this repo as it is useless.
There are other projects that does it better than openai-pr:
- https://github.com/Codium-ai/pr-agent
- https://githubnext.com/projects/copilot-for-pull-requests  <- this one might be useful to you as you work in Microsoft environment
Best,
